#---------------------
# Author: tboyarski
# Date: 2017-06-07.10-42-31
#---------------------


#################################
# ----- Global Variables ------ #
#################################
#       -- Parameters --        #
shellCallFile: shellCalls.txt
offCluster: True
fastqKEEP: True
intermediateKEEP: False
refFILE: GRCh37-lite.fa
chrLIST: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'MT', 'GL000207.1', 'GL000226.1', 'GL000229.1', 'GL000231.1', 'GL000210.1', 'GL000239.1', 'GL000235.1', 'GL000201.1', 'GL000247.1', 'GL000245.1', 'GL000197.1', 'GL000203.1', 'GL000246.1', 'GL000249.1', 'GL000196.1', 'GL000248.1', 'GL000244.1', 'GL000238.1', 'GL000202.1', 'GL000234.1', 'GL000232.1', 'GL000206.1', 'GL000240.1', 'GL000236.1', 'GL000241.1', 'GL000243.1', 'GL000242.1', 'GL000230.1', 'GL000237.1', 'GL000233.1', 'GL000204.1', 'GL000198.1', 'GL000208.1', 'GL000191.1', 'GL000227.1', 'GL000228.1', 'GL000214.1', 'GL000221.1', 'GL000209.1', 'GL000218.1', 'GL000220.1', 'GL000213.1', 'GL000211.1', 'GL000199.1', 'GL00217.1', 'GL000216.1', 'GL000215.1', 'GL000205.1', 'GL000219.1', 'GL000224.1', 'GL000223.1', 'GL000195.1', 'GL000212.1', 'GL000222.1', 'GL000200.1', 'GL000193.1', 'GL000194.1', 'GL000225.1', 'GL000192.1']
#       -- Directory --         #
inputDIR: input
refDIR: ref
outputDIR: output
bamDIR: bam
metricsDIR: metrics
#         -- Sample --          #
sample: ['Pfeiffer1', 'Pfeiffer2']
sampleFILE: input/sampleFILEsingle.txt
sampleFORMAT: single
#################################


#################################
# ----- utils Parameters ------ #
#################################
#       -- Software --          #
utils_picardProg: picard
utils_javaProg: java -Xmx2G
utils_snpSiftProg: -jar ~/share/usr/anaconda/4.3.0/envs/CentOS5-APR28-2/share/snpeff-4.1l-0/SnpSift.jar
utils_vcfEffOnePerLineProg: ~/share/usr/anaconda/4.3.0/envs/CentOS5-APR28-2/share/snpeff-4.1l-0/scripts/vcfEffOnePerLine.pl
#    -- Shared Variables --     #
vcfSampleSingle: 0 
vcfGenIDsSingle: GT GQ SDP DP RD AD FREQ PVAL RBQ ABQ RDF RDR ADF ADR 
vcfInfoFieldsDbSnp: CDA KGValidated OM PM GMAF
vcfGenFieldsSingle: GEN[0].GT GEN[0].GQ GEN[0].SDP GEN[0].DP GEN[0].RD GEN[0].AD GEN[0].FREQ GEN[0].PVAL GEN[0].RBQ GEN[0].ABQ GEN[0].RDF GEN[0].RDR GEN[0].ADF GEN[0].ADR  
vcfSamplePair: 0 1 
vcfGenIDsPair: GT GQ DP RD AD FREQ DP4 
vcfInfoFieldsPair: DP SS SSC GPV SPV CDA KGValidated OM PM GMAF
vcfGenFieldsPair: GEN[0].GT GEN[1].GT GEN[0].GQ GEN[1].GQ GEN[0].DP GEN[1].DP GEN[0].RD GEN[1].RD GEN[0].AD GEN[1].AD GEN[0].FREQ GEN[1].FREQ GEN[0].DP4 GEN[1].DP4  
vcfFields: CHROM POS ID REF ALT QUAL FILTER
effFields: ['"EFF[*].EFFECT"', '"EFF[*].IMPACT"', '"EFF[*].FUNCLASS"', '"EFF[*].CODON"', '"EFF[*].AA"', '"EFF[*].GENE"', '"EFF[*].BIOTYPE"', '"EFF[*].CODING"', '"EFF[*].TRID"', '"EFF[*].RANK"']
utilsDIR: utils
#    -- sam2BAM Specific --     #
Sam2BamARGS: -bS
samDIR: sam
#  tableMERGE_ADAPTOR Specific  #
#  vcfGetTable_ADAPTOR Specific #
OnePerLineFLAG: False
#    vcfMERGE_ADAPTOR Specific  #
#    vcfSORT_ADAPTOR Specific   #
vcfSORTInputDIR: varScan
vcfSORTValStringency: VALIDATION_STRINGENCY=LENIENT
vcfSORTMaxRec: MAX_RECORDS_IN_RAM=5000000
vcfSORTSeqDict: ~/share/references/genomes/gsc/GRCh37-lite.dict
#################################


#################################
# ----- annotateVcf Parameters ------ #
#################################
#       -- Software --          #
annotateVcf_javaProg: java -Xmx2G
annotateVcf_snpSiftProg: -jar ~/share/usr/anaconda/4.3.0/envs/CentOS5-APR28-2/share/snpeff-4.1l-0/SnpSift.jar
annotateVcf_snpEffProg: -jar ~/share/usr/anaconda/4.3.0/envs/CentOS5-APR28-2/share/snpeff-4.1l-0/snpEff.jar
#    -- Shared Variables --     #
sampleFORM: "varType annotated\nsnp .canonical_annotated.dbsnp_annotated.cosmic_annotated\nindel .canonical_annotated.indel_annotated\n"
annotateVcfDIR: annotateVcf
annotateVerbose: -v
annotateID: -id
annotateDbSnp: ~/share/references/dbsnp/dbsnp_137.hg19.vcf
snpEffGenomeVersion: GRCh37.72
snpEffConfig: -c ~/share/usr/anaconda/4.3.0/envs/CentOS5-APR28-2/share/snpeff-4.1l-0/snpEff.config
snpEffFormat: -i vcf
snpEffDownstream: -no-downstream
snpEffIntergenic: -no-intergenic
snpEffUpstream: -no-upstream
snpEffgatk: -o gatk
snpEffgatk: -o gatk
snpEffTranscript: ''
snpEffHGVS: -hgvs
#   -- canonical Specific --    #
#     -- cosmic Specific --     #
snpSiftCosmic: ~/share/references/cosmic/CosmicCodingMuts_v68.hg19.fixed.sort.vcf
#     -- dbsnp Specific --      #
#      -- indel Specific --     #
knownIndel1000G: ~/share/references/1000g/1000G_phase1.indels.hg19.with_id.vcf
knownIndelMills1000G: ~/share/references/1000g/Mills_and_1000G_gold_standard.indels.hg19.with_id.vcf
# -- noncanonical Specific --   #
#################################



#################################
# ---- varScan Parameters ----- #
#################################
#       -- Software --          #
varScan_varScanProg: varscan
varScan_samtoolsProg: samtools
#    -- Shared Variables --     #
vcfProgram: varScan
varType: ['snp', 'indel']
varScanSplitDIR: varScanSplit
varScanDIR: varScan
varScanChrSplit: True
minCOV: --min-coverage 20
minREAD: --min-reads2 10
minQUAL: --min-avg-qual 20
minFREQ: --min-var-freq 0.01
pVALUE: --p-value 0.05
strandFILT: --strand-filter 0
outVCF: --output-vcf 1
minSTRAND: --min-strands2 0
posVALID: --validation 1
#   mpileup2cns_SingleUNSPLIT   #
# mpileup2copycall_PairUNSPLIT  #
#  mpileup2copynum_PairUNSPLIT  #
mapQSkip: -q 1
#    mpileup2vcf_PairUNSPLIT    #
#   mpileup2vcf_SingleUNSPLIT   #
#     mpileup2vcf_PairSPLIT     #
#    mpileup2vcf_SingleSPLIT    #
#################################



#################################
# ----- mpileup Parameters ------ #
#################################
#            Software           #
mpileup_samtoolsProg: samtools
#        Shared Variables       #
mpileupDIR: mpileup
bitFLAG: 512
countORPHAN: -A
noBAQ: -B
maxDEP: -d 10000000
mapQUAL: -q 20
bedFILE: ""
#         mpileupUNSPLIT        #
#          mpileupSPLIT         #
#################################


#################################
# ----- processBam Parameters ------ #
#################################
#       -- Software --          #
processBam_samtoolsProg: samtools
processBam_picardProg: picard
processBam_bwaProg: bwa
processBam_bamsortProg: bamsort
processBam_perlProg: perl
processBam_bammarkduplicates2Prog: bammarkduplicates2
SoftwareChoiceFLAG_sortBAM: biobambam
SoftwareChoiceFLAG_alignBAM: default
#    -- Shared Variables --     #
fastqDIR: fastq
processBamDIR: processBam
picardValStringency: VALIDATION_STRINGENCY=LENIENT
picardMaxRec: MAX_RECORDS_IN_RAM=5000000
#    -- alignBAM Specific --    #
picardCompatibility: -M
coreNumber: -t 4
seqPlatform: ILLUMINA
trimReadsFLAG: False
phred64: -Q 33
firstBaseToKeep: ''
lastBaseToKeep: ''
#    -- bam2fastq Specific --   #
rawBamDIR: rawBam
samtoolsSortMem: 4000000000
#    -- cleanBAM Specific --    #
#    -- fastq2GZ Specific --    #
#     -- fastqc Specific --     #
fastqc: ~/share/usr/fastqc-0.10.1/fastqc.pl
nogroupFLAG: ''
#   -- filteredBAM Specific --  #
filterBitFlag: 512
#   -- fixmateBAM Specific --   #
#    -- indexBAM Specific --    #
fileTAG: _realigned_sorted_filtered_markdup
#   -- markdupBAM Specific --   #
compressLVL: level=-1
#  -- namesortBAM Specific --   #
#    -- rmdupBAM Specific --    #
#   -- sortBAM_* Specific --    #
#################################
